[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[start]
startCommand = "node server.js"

[nixpacks]
# Forçar instalació de Node i Python alhora
languages = ["node", "python"]

[phases.setup]
aptPkgs = ["python3", "python3-pip"]

[phases.install]
cmds = ["pip3 install -r requirements.txt"]
